### ISSUE TITLE
java.io.IOException while building an image of the mediator

### ISSUE THREAD

**Issue by ndigirigijohn** [hyperledger-identus/mediator#216]
Trying to build an image of the mediator to run locally with the command  NODE_OPTIONS=--openssl-legacy-provider sbt docker:publishLocal  but I get an java.io.IOException  as shown in the below images .
![Screenshot from 2024-01-31 10-18-31](https://github.com/input-output-hk/atala-prism-mediator/assets/89837972/0853b366-678f-4971-8c42-9e96fad4e1b3)

![Screenshot from 2024-01-31 10-18-33](https://github.com/input-output-hk/atala-prism-mediator/assets/89837972/0d49e169-4c3f-42c6-acaa-0d3105df0d07)

**Comment by shaileshp0110** [comment]
Look like permission issue
make sure you are not running the command using  sudo   
`NODE_OPTIONS=--openssl-legacy-provider sbt docker:publishLocal `
Please follow the steps below
https://docs.docker.com/engine/install/linux-postinstall/

**Comment by FabioPinheiro** [comment]
Yes. We had a call to help the user on this topic and is now solved.
Let's create three small tasks to improve documentation and close this one.

1- We should never need to run SBT with sudo (root user)
This can lead to problems of permissions to write the folders (like this)
Add something to the troubleshoot section about this.

2- Add instructions to double check if Docker was correctly installed. The user that is building the docker image needs to have access to the socket that talks to the docker system. (and should not be root)
Add also to the troubleshoot section what are the errors when this is not true
https://docs.docker.com/engine/install/linux-postinstall/

3- In the documentation rename `docker-compose` to `docker compose` (for the latest versions of docker)
