### ISSUE TITLE
Docs: Rename docker-compose to docker compose

### ISSUE THREAD

**Issue by FabioPinheiro** [hyperledger-identus/mediator#219]
In our documentation we mention `docker-compose` 

But for some system it's `docker compose` (without the dash).
I think without the dash is the latest version. Since the project was merged or moved to be in docker. 
So let's just rename. I don't think that we need a troubleshoot section. If people only have the `docker-compose` as a separate binary they probably know about this. Either way it's easy to detect and figure out.

**Comment by HenrySaya** [comment]
Hello I can handle this task easily

**Comment by FabioPinheiro** [comment]
@HenrySaya that would be awesome.
Btw that is also one mention of `docker-compose` on another repository: https://github.com/input-output-hk/atala-prism-docs/blob/183b19eb119cce6b83bc06fc206e38dfcd446615/documentation/docs/quick-start.md?plain=1#L328

**Comment by FabioPinheiro** [comment]
Fix by PR #220
