### ISSUE TITLE
On live-delivery-change message request to mediator should reply with status response with "live_delivery": true set to true on a connection capable of live delivery

### ISSUE THREAD

**Issue by mineme0110** [hyperledger-identus/mediator#243]
As per the message pickup spec (https://didcomm.org/messagepickup/3.0/ )
When live-delivery-change message is sent on ws (Message Type URI: https://didcomm.org/messagepickup/3.0/live-delivery-change)
mediator response should contain "live_delivery": true  in the status message (Message Type URI: https://didcomm.org/messagepickup/3.0/status)
Though this field is optional it will be nice to have

**Comment by FabioPinheiro** [comment]
I'm going to do a PR for this.
@mineme0110 can we close https://github.com/FabioPinheiro/scala-did/issues/209 . I'm going to the improvements here
