### ISSUE TITLE
Add CONTRIBUTING.md guideline

### ISSUE THREAD

**Issue by mkbreuningIOHK** [hyperledger-identus/mediator#254]
In the [PR template](https://github.com/input-output-hk/atala-prism-mediator/blob/main/.github/PULL_REQUEST_TEMPLATE.md), it is referred to the 'My PR follows the contribution guidelines of this project', and we would like to add the link to that.
As there is no CONTRIBUTING.md file in the mediator repo, this ticket is to:
- Define the CONTRIBUTING.md file and add it.
- Update the PR template with a link to it.
- Take @petevielhaber's [comment](https://github.com/input-output-hk/atala-prism-mediator/pull/252#discussion_r1517827848) into account.

**Comment by mkbreuningIOHK** [comment]
@FabioPinheiro , do you think we can use the same CONTRIBUTING guideline as [OEA's](https://github.com/hyperledger-labs/open-enterprise-agent/blob/main/CONTRIBUTING.md) or one of Wallet SDK's (e.g [Wallet SDK TS'](https://github.com/input-output-hk/atala-prism-wallet-sdk-ts/blob/master/CONTRIBUTING.md)) or it needs to be created from scratch as there are specificity to Mediator? 
If specific, I will let you create it as it will be more efficient.
Otherwise, let me know which file to use as a draft and I can take it by copying and you can make the changes during the review.

**Comment by FabioPinheiro** [comment]
Still TODO:
- Add contribution guideline - https://github.com/input-output-hk/atala-prism-mediator/pull/252#discussion_r1517659539

**Comment by essbante-io** [comment]
As part of the preparations to migrate the repo to Hyperledger, I added a CONTRIBUTING.md file. It references the CONTRIBUTING guidelines from the main Identus repository
cc: @mkbreuningIOHK
