### ISSUE TITLE
Rename Atala PRISM Mediator to Identus Mediator 

### ISSUE THREAD

**Issue by FabioPinheiro** [hyperledger-identus/mediator#255]
- [x] Rename all mentions for Atala or PRISM to Identus
- [x] Rename package `io.iohk.atala.mediator` to `org.hyperledger.identus.mediator`
- [x] #337

**Comment by mkbreuningIOHK** [comment]
@FabioPinheiro , fyi, there is a table for the renaming to use and update: [replacement table]( https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0) 
It's not just the Atala PRISM renaming. It's good if this can be started to see if it is convenient: if you find one instance that is not in the table, you may add it and ask what to rename with to @essbante-io

**Comment by FabioPinheiro** [comment]
Most of the work is done but we still need to fix small things.

**Comment by FabioPinheiro** [comment]
I am now finalizing this

**Comment by FabioPinheiro** [comment]
@yshyn-iohk @essbante-io Can you move the Discord channel from Atala Discord to Hyperledger Discord ?

**Comment by FabioPinheiro** [comment]
Mediator have a channel in Hyperledger Discord now https://discord.com/channels/905194001349627914/1252629675943919679
