### ISSUE TITLE
Cryptographic keys optional?

### ISSUE THREAD

**Issue by mixmix** [hyperledger-identus/mediator#264]
It's unclear from the `0.10.2` docs whether you need to generate your own keys. :fire:  Seems like you would. 

Further, the format was a little unclear to me (I know x25519 + ed25519 from other cryptography work, but didn't know OKP). 
Here's some notes on how I generated keys for my `docker-compose.yml` In Node.js : 

```js
const crypto = require('crypto')

{
  const { publicKey, privateKey } = crypto.generateKeyPairSync('x25519', {
    privateKeyEncoding: { format: 'jwk' },
    publicKeyEncoding: { format: 'jwk' }
  })

  console.log('# x25519 OKP keys')
  console.log(`KEY_AGREEMENT_D=${privateKey.d}`)
  console.log(`KEY_AGREEMENT_X=${publicKey.x}`)
}

console.log('---------')

{
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { format: 'jwk' },
    publicKeyEncoding: { format: 'jwk' }
  })

  console.log('# ed25519 OKP keys')
  console.log(`KEY_AUTHENTICATION_D=${privateKey.d}`)
  console.log(`KEY_AUTHENTICATION_X=${publicKey.x}`)
}
```

**Comment by mineme0110** [comment]
Octet key Pair(OKP) type is used generally in peer did JWK format , Yes we could update our documentation  to make  it more clear

**Comment by shaileshp0110** [comment]
https://github.com/input-output-hk/atala-prism-mediator/pull/267

**Comment by FabioPinheiro** [comment]
@mineme0110 technically I think the key are optional ATM. But it shouldn't be.
We really want the user to setup there on keys.

@mixmix other than also improving the documentation about this, how should we tell the user if he start the mediator with out keys?

After detecting the kids are not set up.
- Should we tell the user that the keys are missing before shutting down and explain what type of keys and how to set up? Or should the mediator start with the default keys (or random keys)?
- Should we generate a random set of key pair. For the user to manually setup the keys?

**Comment by mixmix** [comment]
@FabioPinheiro either of your ideas are fine - auto-generating and persisting keys on startup is a nice (if they don't already exist). I think the main thing is accidentally running production setup with "default" keys is a bomb waiting to go off for this project!

**Another idea**:  have a "dev" mode and "production" mode. dev gets you going easier with all those defaults, production [hits you with a stick then crashes if you don't provide required fields. Maybe you launch the dev with some OBVIOUS env like `UNSAFE_DEV_MODE=true`

**Comment by FabioPinheiro** [comment]
So what we intend to do is to remove the default keys. The application wouldn't start without the keys being set up.

Users needs to generate and set up those if you want to get started with. So we wanted to add a quick guide(s) how to generate those keys.

The code @mixmix show above can be one script uses nodejs generate those keys. I would also prefer to have the possibility of using only bash commands.
Something similar to:
```shell
> openssl genpkey -algorithm ed25519 -out private_key_ed25519.pem

> openssl pkey -inform pem -in private_key_ed25519.pem -noout -text
ED25519 Private-Key:
priv:
    d9:08:d1:f2:c0:e6:a1:ec:d2:38:bb:4d:e7:23:59:
    4b:76:eb:13:b4:fa:2b:4a:14:f9:b6:aa:05:a2:9d:
    e8:36

# parse that HEX into base64
> echo d9:08:d1:f2:c0:e6:a1:ec:d2:38:bb:4d:e7:23:59:4b:76:eb:13:b4:fa:2b:4a:14:f9:b6:aa:05:a2:9d:e8:36 \
  | xxd -r -p \
  | base64  # or basenc --base64url
2QjR8sDmoezSOLtN5yNZS3brE7T6K0oU+baqBaKd6DY=
```

**Comment by mineme0110** [comment]
@FabioPinheiro  I will close this issue against this PR https://github.com/input-output-hk/atala-prism-mediator/pull/267

**Comment by FabioPinheiro** [comment]
Let just want a bit in case @mixmix you want to leave some feedback. Especially about the documentation.
