### ISSUE TITLE
Mediator still has IOHK reference

### ISSUE THREAD

**Issue by mineme0110** [hyperledger-identus/mediator#313]
Please remove this reference 
https://github.com/search?q=repo%3Ainput-output-hk%2Fatala-prism-mediator%20IOHK&type=code

**Comment by FabioPinheiro** [comment]
The only reference we need to rename for now is the html title `<title>IOHK Mediator</title>`.
The emails will be done later

**Comment by FabioPinheiro** [comment]
New link
https://github.com/search?q=repo%3Ahyperledger/identus-mediator%20IOHK&type=code

**Comment by FabioPinheiro** [comment]
Done
