### ISSUE TITLE
Excessive Log File Size Causing Out-of-Memory Error

### ISSUE THREAD

**Issue by chereseeriepa** [hyperledger-identus/mediator#344]
**Description:**
The `identus-mediator` container encountered an out-of-memory error and crashed after running for a while. Upon investigation, it was found that the log file for the container had grown excessively large, reaching a size of 30GB. The log file path was:

```
/var/snap/docker/common/var-lib-docker/containers/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997-json.log
```

**Steps to Reproduce:**
1. Deploy the `atala-prism-mediator@0.14.2` container using Docker Compose.
2. Allow the container to run for an extended period.
3. Monitor the disk usage for the container’s log file.

**Expected Behaviour:**
The log file should be managed in such a way that it does not grow excessively and consume all available disk space, potentially causing the container to crash.

**Actual Behavior:**
The log file grew to 30GB, which led to the container running out of memory and crashing.
![image](https://github.com/user-attachments/assets/3fe9ff6b-41e0-454c-9dfd-0d3c70a6f479)

**Resolution:**
The log file was manually deleted using:
```bash
rm /var/snap/docker/common/var-lib-docker/containers/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997-json.log
```
After deletion, the container was restarted successfully using:
```bash
docker-compose up
```

**Suggested Solution:**
To prevent this issue from recurring, it is recommended to:
1. Implement log rotation for the `identus-mediator` container to manage log file sizes.
2. Configure log rotation settings to ensure that log files are periodically rotated and archived, with a size limit to prevent excessive growth.

#### `docker-compose.yml`
```
services:
  identus-mediator:
    image: ghcr.io/input-output-hk/atala-prism-mediator:0.14.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

...etc
```

**Comment by FabioPinheiro** [comment]
Thanks for the report
I will have a look

**Comment by FabioPinheiro** [comment]
Hey @chereseeriepa
I was concerned that the mediator application was writing logs to the file system.
But we only have two appender in the [logback config file](https://github.com/hyperledger/identus-mediator/blob/main/mediator/src/main/resources/logback.xml).

My concerned was that we were writing files inside of the container. But now I had a better look and I see this file is in the host machine `/var/snap/docker/common/var-lib-docker/containers/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997/d6a5db46fd3a4e5b10e1b7a5bf2c476cb8470f01449973d8b488c40ce3dee997-json.log`.

We don't really specify how it should be run. But I check the documentation and I didn't see anywhere we specifying a logging driver in docker. So my expectation was for the defaults of docker to be good enough.

I was expecting the default logging driver to be something like `local` driver. Instead, the default is the `json-file` driver (and with an unlimited max size)... https://docs.docker.com/engine/logging/configure/#supported-logging-drivers.

---

This is more a feature request / enhancement.
I like the values you suggestion for the `docker-compose.yml`.
```yml
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
```

So feel free to open a PR, It's always nice to have new contributors.
Its a single file so you can easily edit directly from Github. Create a [patch pull request](https://github.com/hyperledger/identus-mediator/edit/main/docker-compose.yml) on that `docker-compose.yml` file.

**Comment by FabioPinheiro** [comment]
I'm still surprise by the default behavior of docker. (I need to check the default of configuration on my Raspberry-pi. I don't want my home to lab to go down :cold_sweat:) 

I'm imagine that if you are running anything in a production level. That default drive would be bad for most containers. You probably want to change the default drive for your docker in general (docker `daemon.json` file).

So in that aspect I'm not a big fan of changing the default behavior of docker. (I like to keep it simple in order to be easy to maintain).

Also wondering if its time to review the log line in the code and move the Level from `INFO` to `DEBUG`.

**Comment by FabioPinheiro** [comment]
I added this page to the documentation website
https://hyperledger.github.io/identus-docs/docs/identus/troubleshooting&considerations

**Comment by FabioPinheiro** [comment]
I'm closing the ticket, but feel free to reopen if you feel the documentation is not enough
