### ISSUE TITLE
Support for subdirectory in SERVICE_ENDPOINTS

### ISSUE THREAD

**Issue by robertocarvajal** [hyperledger-identus/mediator#382]
Sometimes is desirable to run the mediator endpoint in a subdirectory of a webapp to avoid CORS issues, for example, defining `SERVICE_ENDPOINTS='https://www.myapp.com/mediator'`. If you setup the `ProxyPass` on webserver correctly, when you try to load the endpoint it fails trying to load `https://www.myapp.com/public/webapp-fastopt-bundle.js` because the mediator server endpoint is assuming the SERVICE_ENDPOINT is not on a subdirectory and on a web root.

**Comment by FabioPinheiro** [comment]
Just to be sure, this is a limitation of webpage (of the mediator) not the mediator (DIDComm service)?

**Comment by robertocarvajal** [comment]
Yes, forgot to mention, the service seems to still work but the webpage doesn't render.

**Comment by FabioPinheiro** [comment]
I check the `index.html`'s script ref. Where I thought the problem was, but this was fixed even before we fork the project into the IOHK repository.


So I try to put the mediator behind a reverse proxy with nginx.
And this was not a problem


Here is the config file I used in NGINX (`nginx.conf`):

```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    server {
        listen       9090;
        server_name  localhost;
        location ^~ /app/ {
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_pass https://mediator.atalaprism.io/;
        }    
    }
    include servers/*;
}
```

**Comment by FabioPinheiro** [comment]
So in here 
https://github.com/hyperledger/identus-mediator/blob/main/mediator/src/main/scala/org/hyperledger/identus/mediator/IndexHtml.scala#L28

` <script type="text/javascript" src="public/webapp-fastopt-bundle.js"></script>`

The path is already a relative reference

**Comment by FabioPinheiro** [comment]
@robertocarvajal feel free to reopen with you still think that is a problem.
